
CREATE DATABASE IF NOT EXISTS burgers_db;


USE burgers_db;
DROP TABLE IF EXISTS burgers;

CREATE TABLE burgers (
id INTEGER AUTO_INCREMENT,
burger_name VARCHAR(250) NOT NULL,
devoured BOOLEAN DEFAULT false,
PRIMARY KEY (id)
);